kouxi08/Hontokun-frontend

cspell/dictionary.txt
postcss.config.js
src/components/HelloWorld.vue
src/index.css
src/main.js
tailwind.config.js

ライブラリのセットアップ
- tailwind
- primary, secodary, accent, dangerの設定
- font(ZenMaruGothic NotoSansJP)の導入
- pinia
- storeディレクトリを追加
-  #17

ライブラリのセットアップ

---

changelog.config.js
package-lock.json
package.json

コミットメッセージを統一化
- git-czをインストール
- git-czで規則通りのコメントを書くことができる
✅ Closes: #29

コミットメッセージを統一化

---

.eslintrc.js
.github/ISSUE_TEMPLATE/config.yml
src/components/ButtonComponent.vue

✅ Closes: #44
#44
- url先が自分のレポジトリになっていたのを修正

[fix] 44 config.ymlのurlを修正

---

public/index.html
src/App.vue
src/components/Header.vue
src/components/HeaderComponent.vue

- #12 
ヘッダーのコンポーネントの作成
- header.vueの追加
- app.vueの変更

[コンポーネント作成]ヘッダーコンポーネントの作成

---

.eslintrc.js
src/App.vue
src/components/FooterComponent.vue
src/components/HeaderComponent.vue

- #13
フッターコンポーネントの作成
- FooterComponent.vueの作成
- App.vueの更新

フッターコンポーネントの作成

---

src/components/IconComponent.vue

- #57 
アイコンコンポーネントの修正
- 親要素を削除

アイコンコンポーネントの修正

---

src/components/page/loadingPage.vue
src/components/page/topPage.vue
src/main.js

[add] refs 35 ローディング画面の作成

---

public/icons/close-circle.svg
public/icons/tooltip.svg
src/components/toolipComponent.vue

- #31
ツールチップコンポーネントの作成
- ツールチップできた

[add] refs 31 ツールチップコンポーネントの作成

---

src/components/IconComponent.vue
src/components/InputComponent.vue
src/components/LevelComponent.vue
src/components/MessageComponent.vue
src/components/XpComponent.vue
src/components/page/difficultyPage.vue
src/components/page/loginPage.vue
src/components/page/mainPage.vue
src/components/page/signupPage.vue
src/components/page/topPage.vue

- #70 
エンドタグに追加
- <img> <br>タグにセルフエンドタグ追加
- <textarea>にエンドタグ追加

[fix] refs 70 エンドタグ追加

---

src/components/page/loginPage.vue
src/components/page/signupPage.vue

- #34 
ログインと新規登録画面からTopPageに戻るボタンをつけた
- ログインと新規登録画面からTopPageに戻るボタンをつけた

[update] refs 34 topPageに戻るボタンつけた

---

src/components/page/topPage.vue

- #86
ネコの画像サイズを固定に修正
- ネコの画像サイズを固定に修正

ネコの画像サイズを固定に修正

---

src/components/page/modePage.vue

#93 
モード画面のモード選択ボタン別に色が変わるようになった

[update] refs 93 モードのボタン別の色に調整

---

src/main.js

routeのimportを修正

---

src/components/page/loginPage.vue
src/components/page/signupPage.vue

- #109
ログイン、新規登録画面からtopPageん戻るボタンの処理を追加

[update] refs 109 backボタン処理の追加

---

charts/hontokun/Chart.yaml
charts/hontokun/values.yaml

-  #66
imageのバージョン指定の仕方が間違っていたので修正、ingressClassNameの指定忘れがあったのでそこも修正
- imageのバージョンを修正
- ingressClassNameに"nginx"を挿入して正常に動作できるようにした

[update] refs 66 Chartの修正

---

src/components/InputComponent.vue
src/components/page/loginPage.vue
src/components/page/signupPage.vue

- #77
ログインと新規登録のInputのラベルの追加
Placeholderの変更
Inputの上下幅の調整

[update] 77 refs ラベルの追加&上下幅調整

---

.gitignore
src/firebase.js

firebase.jsonに変更

---

README.md

- https://github.com/kouxi08/Hontokun-frontend/issues/127
Helmを使用したinstall方法を記述した
- READMEの追記

[update] refs 127 READMEの追記

---

src/components/modules/ButtonComponent.vue
src/components/modules/MessageComponent.vue
src/components/modules/NewsComponent.vue
src/components/modules/TableComponent.vue
src/components/page/battlePage.vue
src/components/page/difficultyPage.vue
src/components/page/mainPage.vue
src/components/page/modePage.vue
src/components/page/profilePage.vue
src/components/page/resultPage.vue
src/main.js
src/stores/Page.js

- Issue番号（例: `#123`）
-  #120 
- #122 
- #123 
- #124 
- #125 
- #126 
- piniaでの画面遷移を削除
- vue-routerの遷移に変更
- テーブルコンポーネントに白背景を追加
- メイン画面のユーザー名を変数で持つように変更
- プロフィール画面から戻るときに前の画面に遷移するように変更
- 結果画面でボタンの遷移先を追加
- ニュースコンポーネントの解説と報告ボタンのサイズをxsに変更
- ボタンコンポーネントを押下時にdisableを追加
- ボタンコンポーネントのdisable時の背景色追加

[fix] refs #120 #122 #123 #124 #125 #126 修正

---

.gitignore
package-lock.json
package.json
src/axiosInstance.js
src/components/page/difficultyPage.vue
src/components/page/loginPage.vue
src/components/page/mainPage.vue
src/components/page/modePage.vue
src/components/page/profilePage.vue
src/components/page/signupPage.vue
src/components/page/topPage.vue
src/main.js

モード選択画面まで結合

---

src/components/modules/CardComponent.vue
src/components/pages/profilePage.vue
src/main.js

[add] refs 159 profile結合完成

---

src/components/modules/ButtonComponent.vue
src/components/pages/loginPage.vue
src/components/pages/signupPage.vue

[fix] refs 161 button disabled修正

---

src/components/modules/ButtonComponent.vue

[fix] refs 161 修正

---

src/components/pages/notFoundPage.vue
src/components/pages/profilePage.vue

[fix] refs 167 168 169 修正

---

cspell/dictionary.txt
src/components/pages/loginPage.vue
src/components/pages/mainPage.vue
src/components/pages/signupPage.vue

google認証と匿名認証の修正

---

src/components/pages/battlePage.vue
src/components/pages/resultPage.vue

- #100 
- クイズの問題取得・結果取得を追加
- answers(ユーザの回答)の受け渡しできてないです

クイズ取得・結果取得の結合

---

charts/hontokun/values.yaml
docker/Dockerfile.prod
nginx.conf
public/.htaccess

178
- https://github.com/kouxi08/Hontokun-frontend/issues/178
.htaccessを追加してリダイレクトさせるように修正
- .htaccessの追加
追加
- index.htmlへ遷移するconfを追加
- dockerfile.prodでdefault.confをコピーする行を追加

[add].htaccessの追加

---

src/components/pages/resultPage.vue

[fix] refs 181 背景修正

---

nginx.conf

-178
nginx.confの記述でミスを発見したのでその修正です

[fix] refs 178 nginx.confの修正

---

.github/workflows/docker.yaml
charts/hontokun/Chart.yaml
src/components/pages/mainPage.vue

[fix] refs ログイン処理修正

---

src/components/modules/InputComponent.vue
src/components/pages/loginPage.vue
src/components/pages/mainPage.vue
src/components/pages/profileDetailPage.vue
src/components/pages/profileEditPage.vue
src/components/pages/profilePage.vue
src/components/pages/resultPage.vue
src/components/pages/signupPage.vue
src/stores/User.js

- #196
booleanに変更
- 文字列TRUEをbooleanのtrueに変更
- inputコンポーネントのリファクタリング_

boolean fix

---

src/components/pages/battlePage.vue
src/components/pages/resultPage.vue
src/stores/Quiz.js

- #211 
-  マルバツ押すたびにストアリセットを修正
- 結果からテーブルに反映するように変更

[fix] refs 211 マルバツ押すたびにリセットを修正&結果からテーブルに
